development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: otazkyprocr_development
  pool: 5
  username: otazkyprocr
  password: otazkyprocr

test: &test
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: otazkyprocr_test
  pool: 5
  username: otazkyprocr
  password: otazkyprocr

production:
  adapter: postgresql
  encoding: unicode
  database: otazkyprocr_production
  pool: 5
  username: otazkyprocr
  password:
cucumber:
  <<: *test